export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAIL = "SUBMIT_FAIL";

export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";

export const VALIDATE_IBAN_REQUEST = "VALIDATE_IBAN_REQUEST";
export const VALIDATE_IBAN_SUCCESS = "VALIDATE_SUCCESS";
export const VALIDATE_IBAN_FAIL = "VALIDATE_FAIL";
